I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 183, in script call
    call outalive
  File "game/script.rpy", line 1042, in script
    with fade (2.0, 1.0, 2.0)
  File "game/script.rpy", line 1042, in <module>
    with fade (2.0, 1.0, 2.0)
Exception: Not a color: 2.0

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 183, in script call
    call outalive
  File "game/script.rpy", line 1042, in script
    with fade (2.0, 1.0, 2.0)
  File "renpy/ast.py", line 1390, in execute
    trans = renpy.python.py_eval(self.expr)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1042, in <module>
    with fade (2.0, 1.0, 2.0)
  File "renpy/curry.py", line 48, in __call__
    return self.callable(*(self.args + args), **merged_kwargs)
  File "renpy/display/transition.py", line 230, in Fade
    widget = renpy.display.image.Solid(color)
  File "renpy/display/imagelike.py", line 49, in __init__
    self.color = renpy.easy.color(color)
  File "renpy/color.py", line 194, in __new__
    raise Exception("Not a color: %r" % (color,))
Exception: Not a color: 2.0

Windows-10-10.0.19041
Ren'Py 7.4.3.1414
Market Meltdown Test.1.0
Sun Apr 24 14:44:39 2022
